name: Go CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

  deploy:
    name: Deploy to EC2
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build application
      run: |
        go mod download
        CGO_ENABLED=0 GOOS=linux go build -o go-crud-app cmd/main.go

    - name: Debug Information
      run: |
        echo "Built application size:"
        ls -lh go-crud-app
        echo "Checking SSH host:"
        nc -vz ${{ secrets.SSH_HOST }} 22 || echo "Cannot connect to host"

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "go-crud-app"
        target: "/opt/go-crud-app"
        debug: true

    - name: Execute remote commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Current directory: $(pwd)"
          echo "Checking application directory:"
          ls -la /opt/go-crud-app
          sudo systemctl daemon-reload
          sudo systemctl restart go-crud
          sudo systemctl enable go-crud
          sudo systemctl status go-crud